""" Copyright (c) 2026 ARCASCEND DIGITECH PRIVATE LIMITED. All rights reserved.
This file is part of the Donor Report Automation System (DRAS) project.
Author: Jerusha Caroline Raj A Created: 2026-06-30
Description: Initial Django migration for the dras_app application,
declaring the unmanaged Donors, EmailLog, Missionaries, and
SponsorReportHistory models so Django's ORM is aware of their schema. """

# Generated by Django 6.0.6 on 2026-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration declaring the DRAS application's data models.

    Registers the unmanaged ``Donors``, ``EmailLog``, ``Missionaries``,
    and ``SponsorReportHistory`` models with Django's migration state.
    Since these models use ``managed = False``, this migration does
    not create or alter any actual database tables; it only informs
    Django's ORM of the existing schema shape.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Donors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_to', models.CharField(max_length=255)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Email_Log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Missionaries',
            fields=[
                ('missionary_id', models.AutoField(primary_key=True, serialize=False)),
                ('missionary_name', models.CharField(max_length=255)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'Missionaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorReportHistory',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_file_name', models.CharField(max_length=500)),
                ('report_month', models.IntegerField(blank=True, null=True)),
                ('report_year', models.IntegerField(blank=True, null=True)),
                ('email_sent', models.CharField(blank=True, max_length=1, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('email_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sponsor_Report_History',
                'managed': False,
            },
        ),
    ]
